language: node_js
#node_js: stable
 
# S: Build Lifecycle
before_install:
- npm install -g hexo
- npm install -g hexo-cli


install:
  - npm install
 
 
#before_script:
 # - npm install -g gulp
 
script:
  - hexo clean
  - hexo g

after_script:
  - git pull
  - cd ./public
  - git init
  - git config user.name "hxjg"
  - git config user.email "zhangjie@hexinjingu.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${HXJG_BLOG_TOKEN}@${BLOG_REF}" master:master
# E: Build LifeCycle
 
branches:
  only:
    - master
env:
 global:
   - BLOG_REF: github.com/hxjg/hxjg.github.io.git
